### PR TITLE
Fix canonical generation for CMS category

### PR DESCRIPTION
**Pull request by JavierElices**
As requested, this change adds coverage for cms-category cases.

### CODE REVIEW

**Comment by ghost** [comment]
Hi @jelicesv,
  thanks for your work.

I have some perplexity about these lines:

```
            // Define language and shop from PS context
    $id_lang = $this->context->language->id;
    $id_shop = $this->context->shop->id;
```

these variables are passed as function parameters, but your patch is overriding their value ...

Have you a real world case in which removing these lines makes things broken?
Are they necessary?

Thanks

**Comment by JavierElices** [comment]
Hello,

  You are most certainly right. I have seen places where values are not assigned to these variables and decided to make sure they had the right value.

  Unfortunately, all the final testing I have done was with those lines in. I will do some more testing without them and let you know.

  Regards.

**Comment by ghost** [comment]
@jelicesv Thank you .. I'll wait for your tests then

**Comment by ZiZuu-store** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;pbV4IbnF&#x2F;5-404-on-cms-category"> 404 on CMS Category </a>

**Comment by ZiZuu-store** [comment]
Merged, will remove the lines in dev .. plz confirm they are superfluous

**Comment by ghost** [comment]
@jelicesv please confirm **current dev** is ok for you .. 
thank you for your contribution

**Comment by JavierElices** [comment]
Hello,

  After some testing I have seen that the line:

```
$id_lang = $this->context->language->id;
```

  is necessary for this case to work:

```
case 'blogleoblog':
    $blog = new LeoBlogBlog( $_GET['id'], $id_lang );
    $_params = $_GET;
    $_params['rewrite'] = $blog->link_rewrite;
    $canonical = $link->getModuleLink($module, $controller, $_params, null, $id_lang, $id_shop);
    break;
```

  This bit is only for the Blog module in Leo Theme templates. The rest of the cases seem to be working fine. I suspect that this parameter does not always get passed correctly but since a null value is fine with most subsequent calls, the rest of the cases seem to work.

  Best Regards.

**Comment by ghost** [comment]
@jelicesv this is very strange and unlikely .. 

This function has to be called even for non-current language (for hreflang handling) so forcing the use of the current lang is an error ..

It should be investigated when and why you need to do this

**Comment by JavierElices** [comment]
Don´t worry. Leave the lines out. We have tested and need them for a module you are not adding in this branch.

**Comment by ghost** [comment]
@jelicesv ok 

thank you for your contributions

**Pull request merged**
