### PR TITLE
Add support for blog of Leo Theme

### PR DESCRIPTION
**Pull request by JavierElices**
This change adds support for Leo Theme custom blog module, "blogleoblog".

### CODE REVIEW

**Comment by JavierElices** [comment]
This change adds support for Leo Theme custom blog module, "blogleoblog".

**Comment by ZiZuu-store** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;pbV4IbnF&#x2F;5-fix-cms-category-link"> Fix CMS Category link</a>

**Comment by ghost** [comment]
see #34

**Comment by ghost** [comment]
Leo Blog support merged into a customised **[hack-branch](https://github.com/ZiZuu-store/zzSEOtk/tree/leoblog_support_hack)**

@jelicesv please try if it works for you .. I think the only place where `$id_lang` has to be not-null could be the Blog class instantiation .. please check

Thank you

**Pull request closed without merging**
