### PR TITLE
Name in lower case

### PR DESCRIPTION
**Pull request by numanWD**
When you are using camelCase in the class, the folder and the filename must be lowercase.

With this small amend the module is working 👍 

TODO: Fix the translations with the new name

### CODE REVIEW

**Comment by drAlberT** [comment]
Ok, maybe a good compromise could be to follow the "new" PS trend https://github.com/PrestaShop/ps_categoryproducts ..

what about using `faktiva_seotk` ?

**Comment by numanWD** [comment]
Okss I will refactor with:

folder: `faktiva_seotk`
php_file: `faktiva_seotk.php`
class: `Faktiva_Seotk `
class->name :`faktiva_seotk`

**Comment by numanWD** [comment]
I have tested and works with the new modification

**Comment by drAlberT** [comment]
thanks @numanWD , will review deeper and merge on master ASAP :)

**Comment by numanWD** [comment]
Awesome

**Pull request merged**
